### ISSUE TITLE
unable to authenicate

### ISSUE THREAD

**Issue by Ravan1190** [itszechs/DriveStream#100]
how to setup rclone ? I get this error "Access blocked: can only be used within its organisation".

Error 403: org_internal

**Comment by itszechs** [comment]
> how to setup rclone ?

Refer here please https://rclone.org/drive/


> I get this error "Access blocked: can only be used within its organisation".
> 
> Error 403: org_internal

Not sure what you're referring to here, the release build (with rclone's client id) works just fine
