### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by myfender** [itszechs/DriveStream#101]
Hi, I have an error when try to authenticate.
I configured everything on the drive console.
I am having several difficulties in making it work, there is no detailed step by step?
![Screenshot_20230303-131017_Firefox](https://user-images.githubusercontent.com/3018311/222717656-3b7745bb-ad9f-4442-8a85-32dc307bd9f1.jpeg)

**Comment by itszechs** [comment]
This is not an error, you're supposed to copy the url from address bar and paste it in app (there is a option at the bottom of screen, which says exactly what you need to do)

**Comment by myfender** [comment]
ah ok, thanks
