### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by BIGEAZY289** [itszechs/DriveStream#102]
Getting this error for a while now.

**Comment by cirinium** [comment]
Bro I thought your comments is not loading 😅 lmao your comment itself is getting this error for a while like wait for a while some error

**Comment by itszechs** [comment]
Create your own client id, using rclone's is really not advised as it has way to many users are this point.

Refer here for guide: [#making-your-own-client-id](https://rclone.org/drive/#making-your-own-client-id)

**Comment by BIGEAZY289** [comment]
Sure
