### ISSUE TITLE
The site can't be reached

### ISSUE THREAD

**Issue by vvshel** [itszechs/DriveStream#104]
Hi, Dear Developer ,

I'm using the latest version 1.3.0 of Drivestream . But facing " the site can't be reached" while trying to sign in. 
Could you please help me out with what do I need to do?

Thanks in advance

**Comment by vvshel** [comment]
![20230324_075525](https://user-images.githubusercontent.com/128762100/227402118-b8a10c87-b169-4989-8f81-9a6b132fe1bd.jpg)
![Uploading Screenshot_20230324-075331_Opera.jpg…]()

**Comment by vvshel** [comment]
![Uploading Screenshot_20230324-075331_Opera.jpg…]()

**Comment by itszechs** [comment]
Your screenshots haven't been uploaded. Although I believe it's same as #101. 
Refer to my [comment](https://github.com/itszechs/DriveStream/issues/101#issuecomment-1453486204) there.

**Comment by vvshel** [comment]
> Your screenshots haven't been uploaded. Although I believe it's same as #101. Refer to my [comment](https://github.com/itszechs/DriveStream/issues/101#issuecomment-1453486204) there.

Yes, you are right. 
I know now how to proceed .
It's working now. 
Thank a lot
