### ISSUE TITLE
Release new apk version.

### ISSUE THREAD

**Issue by ronin08** [itszechs/DriveStream#109]
As you've made some changes in the past few days regarding 'client IDs and secret'. But I couldn't find the new version of the app in releases. 

Please add the new version, as I'm facing lots of time-out error and Error 403.

**Comment by itszechs** [comment]
The release is forthcoming and you will be notified within the app when it becomes available for download.

It is not necessary to create issues of this nature. As this application is open-source, you have the option to build the APK yourself if you desire immediate access to new features upon implementation.
