### ISSUE TITLE
Client ID & SECRET

### ISSUE THREAD

**Issue by SwordKing69** [itszechs/DriveStream#110]
Bro please tell where to add client ID and client Secret. Please confirm whether to add Client ID and Client Secret in any one of the files in the given app code or somewhere to add in google console project. Please explain this in detail bro so that I can use my own client secret ID and secret to use this app seamlessly without any 403 errors.

**Comment by ronin08** [comment]
To use your credentials you have to edit this (https://github.com/itszechs/DriveStream/blob/master/app/src/main/java/zechs/drive/stream/utils/util/Constants.kt) and fill accordingly. And then build the apk from github repository yourself to use it.

Or you can wait for few days till the new version comes out.

**Comment by itszechs** [comment]
Make sure to clone the correct version of DriveStream as the method suggested by @ronin08 is only supported until [v1.3.0](https://github.com/itszechs/DriveStream/tree/1.3.0). Also, [v1.3.1](https://github.com/itszechs/DriveStream/tree/1.3.1) has just been released, which eliminates the need for the rebuilding process.

**Comment by Sunny-Shani** [comment]
Can you please tell me what should I put in "Redirect uri"?

**Comment by itszechs** [comment]
@Sunny-Shani you can follow the [video attached ](https://github.com/itszechs/DriveStream?tab=readme-ov-file#note)

**Comment by ronin08** [comment]
@itszechs hey zechs! hope you're doing well.
Anything new coming or it'll be left untouched until something get broken?

**Comment by itszechs** [comment]
@ronin08 This project is open to public contributions. Otherwise, if anything breaks, I will fix it.
