### ISSUE TITLE
some questions regarding new update 

### ISSUE THREAD

**Issue by Kira-0007** [itszechs/DriveStream#111]
Hello bro, first of all thank for this new update and video guidence but i have some questions in mind please can you help me with it.
1. With this one id & secret in how many devices i can login

2. What stuffs & procedure i need to do to validate my app

3. If app no validate & test app work for 7 days only so what steps i need to do after 7 days

Please can you help me with these questions

**Comment by itszechs** [comment]
> 1. With this one id & secret in how many devices i can login

Afaik unlimited. You're limited by how many emails you can sign up with _aka user cap_ (100 users without verification)

> 2.  What stuffs & procedure i need to do to validate my app

Not sure, also not required for personal use (unless you plan on using 100+ emails). Anyways, I'm sure you can find docs related to it.

> 3. If app no validate & test app work for 7 days only so what steps i need to do after 7 days

No. I've never heard of this! Where does it say that? My personal OAuth Client was created almost 3 years ago now. Unverified. 


Checkout: `APIs & Services` -> `OAuth consent screen` to get familiar with the limits on Google Cloud Console.

**Comment by Kira-0007** [comment]
![Screenshot_2023-04-03-21-35-02-776-edit_org mozilla firefox](https://user-images.githubusercontent.com/105588608/229565962-f045620d-4c2b-4a5c-a17b-d492d721aa84.jpg)

Thnkx bro for all info.. from above ss thats why i was asking point 3rd.

**Comment by Kira-0007** [comment]
Still I don't understand about 100 emails+ thing.. can you please elaborate in easy way 😄

**Comment by SwordKing69** [comment]
> Still I don't understand about 100 emails+ thing.. can you please elaborate in easy way 😄

I think Zech is not aware of the new policy by Google Published on 24 February 2023 which puts restriction on using Oauth client because after 7 days we again have to repeat the steps because the app is not verified. 
And according to latest article by Google we have to verify our app in order to Publish it publically and use it for unlimited use.
So yeah it's not as good as we expect but at last what we can do is just do the procedure regularly in order to enjoy our Videos. :)

**Comment by itszechs** [comment]
@Kira-0007 @SwordKing69 

According to the [Google Cloud Platform documentation](https://shrinkme.vercel.app/hjdppfjxpi), a refresh token for a project with an OAuth consent screen configured for an external user type and a publishing status of “Testing” will expire in 7 days. 

However, in the video at **3:18**, the app is published, so it seems that only one of the two conditions is met.  Therefore, the 7-day expiration does not apply to this app.

If I’ve misunderstood something, please let me know.

**Comment by Kira-0007** [comment]
Well in documentation its talking something about 'GRANT Expire After 7 Days' but lets see after 7 days what will happen.
Btw Thankx for all you efforts & Love Drive Stream ❤️

**Comment by itszechs** [comment]
@Kira-0007  @SwordKing69 It's been 2 weeks now, the app seems to be working just fine, mention if you guys have this issue!?

**Comment by Kira-0007** [comment]
@itszechs yeah working file & perfectly.. thankx for all your efforts 🙌🏻

**Comment by SwordKing69** [comment]
> @Kira-0007 @SwordKing69 It's been 2 weeks now, the app seems to be working just fine, mention if you guys have this issue!?

#98 Please check this out I opened this issue many days ago but still didn't get reply from you. Atleast just tell whether this issue is in your concern or not ? And are you doing anything related this to solve this problem ?
Please reply.
