### ISSUE TITLE
Add More Media Player

### ISSUE THREAD

**Issue by Kira-0007** [itszechs/DriveStream#112]
Heyy..
Is it possible to add more media player or we can choose installed media player from our device ?

**Comment by itszechs** [comment]
> Is it possible to add more media player

Sure! But after `mpv` anything else doesn't make anysense. So to answer your question, No.

> we can choose installed media player from our device

It's not possible since Drive requires authentication, although I think some other Rclone apps for Android do allow that (via proxy server)

**Comment by ronin08** [comment]
@itszechs Why mpv is still in experimental mode? I mean it's great. Consider making it default (with an option to change), irritating to choose player every time.

**Comment by Kira-0007** [comment]
@itszechs then please fix MPV as in experimental mode it have glitches while playing video... Like forward button not work sometimes...

**Comment by fuengfah** [comment]
> > Is it possible to add more media player
> 
> Sure! But after `mpv` anything else doesn't make anysense. So to answer your question, No.
> 
> > we can choose installed media player from our device
> 
> It's not possible since Drive requires authentication, although I think some other Rclone apps for Android do allow that (via proxy server)

I agreed MPV seem to be best choice for player at moment but what mpv-andriod version are you using in v1.3.1

**Comment by itszechs** [comment]
@fuengfah `mpv 0.34.0-361-g3a2838c88d`
