### ISSUE TITLE
PLAYER SUGGESTION

### ISSUE THREAD

**Issue by SwordKing69** [itszechs/DriveStream#118]
Bro I want to ask in reference to the previous 1.3.2 update that which player is more advance, stable and has better capabilities to show high quality video ? 
Is it MPV or Exo Player ??
Please tell me in little detail so that I can confirm which is best for me.

Since in previous Drive Stream Version 1.3.1 whenever we click on any video then it asks from which player to play and there MPV shows up with a bracket says (Experimental) what does that mean and is it now fixed ? Or you have optimi it so that we can play with any video player ??

I want a clear cut answer because it right to know because if that was not the case then there would be no two options to play video. There should be only one and only one best player instead.

Hoping nice explanation from your side.

**Comment by itszechs** [comment]
There is no reason to have ExoPlayer honestly (except for PiP mode), MPV is far superior in every way hence why it's the default player, ExoPlayer remains for legacy support I guess though it would fail to play many codecs.

The next version of the app will allow users to choose their default players. You're free to use whichever you want! Stick with MPV for better playback support is what I'd recommend.
