### ISSUE TITLE
Buffering issue

### ISSUE THREAD

**Issue by Kira-0007** [itszechs/DriveStream#122]
https://github.com/itszechs/DriveStream/assets/105588608/1d8542a7-8d5a-46fc-9b31-6733cdfbe36d

![Screenshot_2023-08-19-22-06-44-873_org mozilla firefox](https://github.com/itszechs/DriveStream/assets/105588608/8389407e-4626-4abc-95d8-91df05794cac)

I don't why it is so much buffering during playing video even wifi speed is good..
Please give me some solution of it please 🙏🏻

Attached video of buffering and wifi speed

**Comment by itszechs** [comment]
You're playing on TV and the speedtest is from the phone.

Though it isn't mentioned anywhere, but Google Drive sort of has a "shadow ban" which limits download speed of a file by alot <2Mbps.
I don't why it happens or when, but it is fixed if your IP Address changes.
This is most likely to be the reason, or your TV is on 2.4Ghz WiFi incapable of providing enough bandwidth for streaming any huge files.

In any case, streaming is handled by mpv and ExoPlayer.

**Comment by Kira-0007** [comment]
I dont know what is main issue but tv is connected to 5Ghz and mostly it works really fine even file is 50gb but sometimes it buffering so much even file is 2gb 🥲

**Comment by itszechs** [comment]
Google Drive sometimes works mysterious ways

**Comment by Kira-0007** [comment]
Ok bro.. if you say so.. thnkx
