### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by SwordKing69** [itszechs/DriveStream#128]
Bro it's been a very long time around 8+ months and there is no update regarding this application. It needs many fixes like subtitles dynamic scaling so that it can fit within the margins, low audio output from stream, slow connections, Buffering, etc.

Please I am waiting for you to get active again and release a very major update soon.

**Comment by itszechs** [comment]
> subtitles dynamic scaling

https://github.com/itszechs/DriveStream/issues/98

> low audio output from stream

Please check your video files (or speakers perhaps), there is no low audio issue.

> slow connections, Buffering, etc

Please check your connection and size of the file you're trying to stream.
