### ISSUE TITLE
Green flashing when playing big files on Android TV

### ISSUE THREAD

**Issue by ghost** [itszechs/DriveStream#130]
I have an android tv box 4gb+32gb, when playing big files over 500mb there is green flashing while audio still works. Uses both of the players. This is what it looks like
![20241129_225342](https://github.com/user-attachments/assets/465f630a-0f52-4a21-ab0c-4893649f55aa)
There is no issue playing the videos on my Samsung  A54

**Comment by itszechs** [comment]
are you able to play the same file using [mpv-android](https://github.com/mpv-android/mpv-android)?

**Comment by ghost** [comment]
> are you able to play the same file using [mpv-android](https://github.com/mpv-android/mpv-android)?

It doesn't work with neither players, ExoPlayer and mpv don't work. 
Quick note, VLC does work when I play 1GB videos from OneDrive, so maybe it would be nice to also implement vlc

**Comment by itszechs** [comment]
didn't not answer my question

**Comment by ghost** [comment]
It doesn't work with mpv, I don't know what else you mean

> didn't notice answer my question

**Comment by ghost** [comment]
Can we contact on Discord so we can talk in real time
I sent you a friend request a day or two ago

**Comment by itszechs** [comment]
> It doesn't work with mpv, I don't know what else you mean
> 
Checkout the repository I linked, download the video file and try playing using mpv-android

**Comment by ghost** [comment]
> 

> > It doesn't work with mpv, I don't know what else you mean
> 
> Checkout the repository I linked, download the video file and try playing using mpv-android

Downloading the files of course is gonna work but I want to stream the files directly, is there a solution for this streaming issue

**Comment by itszechs** [comment]
> Downloading the files of course is gonna work

Did you try this? or are just assuming?
