### ISSUE TITLE
Application Blocked Error

### ISSUE THREAD

**Issue by rinrinx2** [itszechs/DriveStream#28]
![Screenshot_2022-06-25-18-32-22-105_com google android gms](https://user-images.githubusercontent.com/58888200/175780360-67bb8899-9b02-4533-9688-08171faac83f.jpg)

There is a problem with the client secret and key you use. The application is blocked by Google.  no account login

**Comment by itszechs** [comment]
seems i've reached 100 grants

**Comment by itszechs** [comment]
Addressed in https://github.com/itszechs/DriveStream/issues/29
