### ISSUE TITLE
Important information regarding OAuth

### ISSUE THREAD

**Issue by itszechs** [itszechs/DriveStream#29]
> Since the project is not verified and uses sensitive scopes number of grants is limited to 100 so people are advised on creating their own project and using their own client-keys

As mentioned in the README, my console project is not verified and nor do I intent on getting it verified so its limited to 100 OAuth grants, people are advised on making their own projects and configuring them with their own signing keys, app will automatically link with the project based on the key used to sign the apk (no code modification required).

Though this shouldn't be a problem for existing users!

Just recently my project reached 100 grants so my apk-build can no longer be used by new users they are required to compile the app using their own keys.

Build instructions are provided in [README](https://github.com/itszechs/DriveStream#how-to-build)

**Comment by rinrinx2** [comment]
Can you add the global verification method used in rclone, many applications are using the login URL in rclone

**Comment by itszechs** [comment]
What do you mean by "global verification method"?  I don't think OAuth has such a thing, if it does please link me the documentation.

> many applications are using the login URL in rclone

Are you saying to using rclone's client-id & secret for Oauth in this app? I'm not sure they allow that

**Comment by rinrinx2** [comment]
I've seen many apps use this rclone auth permission

**Comment by itszechs** [comment]
can you link a project? do they really allow that, anyone to use their client-id & secret?

**Comment by rinrinx2** [comment]
https://bdi-generator.hashhackers.com/

For example, see here. For 1 year, this index has been able to log in using auth in this way, everyone and probably 10k entries have been made from here until now.

**Comment by rinrinx2** [comment]
Unfortunately, not many people will be able to use it as there is no entrance anymore.  It's a long job to install android studio and extract it as APK, but thanks for this project.  but i probably won't use it that way

**Comment by itszechs** [comment]
> https://bdi-generator.hashhackers.com/

that's not rclone's, if you click on the `continue to gdi.js.org` you can see developer's info, and that's not rclone.

**Comment by rinrinx2** [comment]
What I want to tell you is that you can create and add a secret key with a free gmail account.

rclone, Air explorer, xplore manager all applications use this system

**Comment by itszechs** [comment]
Unless they're verified they will be limited 100 grants.

Source: [Unverified apps](https://support.google.com/cloud/answer/7454865?hl=en&ref_topic=3473162#)

**Comment by rinrinx2** [comment]
Can you add a detailed readme on how to make an APK and add a secret in this application, at least those who want to use it can do it easily.

**Comment by itszechs** [comment]
> Can you add a detailed readme on how to make an APK and add a secret in this application, at least those who want to use it can do it easily.

Everything required is already in README.

**Comment by rinrinx2** [comment]
Where do we need to enter client id and client secret?

**Comment by itszechs** [comment]
This is no longer an issue since [v1.2.0](https://github.com/itszechs/DriveStream/tree/1.2.0)
