### ISSUE TITLE
Remember and resume from last playback position

### ISSUE THREAD

**Issue by Soffioo** [itszechs/DriveStream#33]
Maybe sometimes happens that you go back by fault, and you need to restart and search the previous point. Can you add it? Thanks to you and other contributors for this project!

**Comment by itszechs** [comment]
You want app to remember last playback position upon exit? Is that right?

**Comment by Soffioo** [comment]
Exactly! So if need to go away from home (for example), you don't need to remember the exact timing to continue the next time.

**Comment by itszechs** [comment]
Understood!

**Comment by ronin08** [comment]
> Understood!

@itszechs can you please add this. 
It's very inconvenient to come back to the movie or show and not remember the last playback position.

One more suggestion is to highlight the last file played in a folder.

All these features and more are present in nplayer but it's login system to drive is outdated. You can view its apk for an idea.
