### ISSUE TITLE
Client id secret and apk

### ISSUE THREAD

**Issue by rinrinx2** [itszechs/DriveStream#35]
hello, where do we need to add client id and secret.  And do I need to use android studio to extract apk

**Comment by Soffioo** [comment]
I tried yesterday to build it, but i didn't understand how to do it

**Comment by rinrinx2** [comment]
yes ı am try but not work failure

**Comment by rinrinx2** [comment]
Unfortunately, the instructions here are only for client id and client secret.  Can you explain how to do this with android studio?  apk build gives an error. can you support this with a video tutorial

**Comment by itszechs** [comment]
@rinrinx2 what problem are you facing? how are you trying to build the project? do you do all the steps before trying to build?

**Comment by rinrinx2** [comment]
I downloaded you GitHub repository completely and then opened it with android studio but unable to build apk

**Comment by itszechs** [comment]
> I downloaded you GitHub repository completely and then opened it with android studio but unable to build apk

You need to first do these steps mentioned [here](https://github.com/itszechs/DriveStream#how-to-build)

As I mentioned before, these steps are valid till v1.1.0 only. So make sure you clone tag [1.1.0](https://github.com/itszechs/DriveStream/tree/1.1.0)

```
git clone --single-branch --branch 1.1.0 https://github.com/itszechs/DriveStream.git
```

**Comment by rinrinx2** [comment]
After this process, where should I enter the client id and secret?

**Comment by rinrinx2** [comment]
Couldn't find the local properties file

**Comment by rinrinx2** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/58888200/176925263-284473b4-19ea-4ef0-8462-d79459b8e67c.png)
error

**Comment by itszechs** [comment]
v1.2.0 released.
