### ISSUE TITLE
AndroidTV: Keyboard doesn't show up automatically 

### ISSUE THREAD

**Issue by Soffioo** [itszechs/DriveStream#41]
I tried to login with my Android Tv but it doesn't show the virtual keyboard ( i tried also Google Home to write with my phone). Is there maybe any script to apply directly the OAuth code?

**Comment by itszechs** [comment]
Interesting, I tried it on my TV and the virtual keyboard does show up.

Did you try selecting the input field?

The keyboard doesn't automatically show up when you open the dialog (which is a bug).

**Comment by Soffioo** [comment]
Here it is, yep i tried, but it doesn't work, my tv is a Sony Bravia KD-55XE9005 4k with Android Tv Stock
![IMG_20220703_094858](https://user-images.githubusercontent.com/32640810/177030444-68842bd1-4122-441c-a359-d0609ab80342.jpg)

**Comment by itszechs** [comment]
Try and use your d-pad to navigate and focus the input field, its kinda hard to tell but i'm pretty sure the "Submit" button is in focus

**Comment by Soffioo** [comment]
Found the "bug" actually: the focus works only with the left move, i used only the up move

**Comment by itszechs** [comment]
Android TV works in mysterious ways, anyways the bug is keyboard not automatically showing up.

**Comment by Soffioo** [comment]
And to change focus you need to click the "left arrow" instead of the "up arrow".
