### ISSUE TITLE
Subtitle button does nothing on AndroidTV(onn android box)

### ISSUE THREAD

**Issue by collectionofcells** [itszechs/DriveStream#53]
When I click the subtitle button in the ExoPlayer(not able to interact with MPV with the remote),nothing happens and the button disappears. Thanks a lot for the development so far

**Comment by itszechs** [comment]
This is not a bug. If the button disappears that means there are no subtitles attached in `.mkv` file.

**Comment by collectionofcells** [comment]
So currently is it not possible to load external subtitles from local machine or from google drive? If so, please consider this feature for future releases, thanks.
