### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by soni0212** [itszechs/DriveStream#62]
Add metadata support from trakt.tv or Plex or any but just add
It will be useful to display media well like infuse does..
![IMG_20221013_183218_333.jpg](https://user-images.githubusercontent.com/32086892/195603531-f5932c21-1922-418a-b73f-fefdc86528b5.jpg)

**Comment by itszechs** [comment]
Definitely a good feature, but out of scope for this app.

I do have another app planned similar to "Infuse", which will be made public soon.
