### ISSUE TITLE
Login problem 

### ISSUE THREAD

**Issue by abhishek1io** [itszechs/DriveStream#63]
pls rply
 when i try to login 
it says  ( Access blocked: rclone’s request is invalid )![IMG_20221025_150054.jpg](https://user-images.githubusercontent.com/81518237/197738179-b8c2afd8-acc2-4837-85aa-6fd77ce1eb08.jpg)

**Comment by ClickWorld99** [comment]
Same Problem...

**Comment by Shayne55434** [comment]
Same here

**Comment by archbishop** [comment]
Same

**Comment by itszechs** [comment]
I'm aware about the current login issue. It will be fixed soon, once I've time from my uni exams.

**Comment by KlausHybrid1001** [comment]
![IMG_20221202_235819](https://user-images.githubusercontent.com/107557518/205361130-1d818cd5-a314-4e96-954d-75d2567196bc.jpg)

Still... Login problem in Android 13. 
Please update

**Comment by Kira-0007** [comment]
Bro please fix this login issue.. i am begging 😭🙏🏻

**Comment by KlausHybrid1001** [comment]
After installing Android 13 nPlayer goes dead, 
Thanx for your great work bro 😊

Is it possible to add features like  -
• Play directly from zip/rar like Mix player
• Brightness bar
• move subtitles/subtitles stay in screen area
