### ISSUE TITLE
Source error

### ISSUE THREAD

**Issue by mayurss786** [itszechs/DriveStream#69]
So many files shows source error

please check this

https://new3.gdtot.cfd/file/8810192053

**Comment by itszechs** [comment]
Upon video playback? what player did you use? what device are you on?

**Comment by mayurss786** [comment]
When i click on file it opens player and then shows Source Error

i am using Exoplayer because mps hangs a lot on my tv

device Hisense 55A73F android 9.0

**Comment by itszechs** [comment]
ExoPlayer only uses built-in decoders so `Source Error` means your device lacks those decoders that the video requires.

mpv on the other hand comes with 3rd party encoders/decoders so it's able handle almost every codec.
If it's laggy then your hardware is weak. It can't be helped.

**Comment by mayurss786** [comment]
Thanks please close it
