### ISSUE TITLE
adjust subtitles position when scaling video 

### ISSUE THREAD

**Issue by KlausHybrid1001** [itszechs/DriveStream#71]
After installing Android 13 nPlayer goes dead,
Thanx for your great work bro 😊

Is it possible to add features like -
• Play directly from zip/rar like Mix player
• Brightness bar
• move subtitles/subtitles stay in screen area

**Comment by itszechs** [comment]
> Play directly from zip/rar like Mix player

I couldn't find anything for `Mix player`, do you mean [MX Player](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad)?
I don't think it's possible to stream files out of an archive format straight from cloud.


> Brightness bar

Existing feature request (#39), it will be worked upon in coming weeks.

> move subtitles/subtitles stay in screen area

I don't think I understand , what you mean by that, can you please elaborate?

**Comment by KlausHybrid1001** [comment]
Sorry for that, App name is " Mixplorer "
and about subtitles
When we stretch to full screen mode , we can't see subtitles ( in some videos).
 So if we can move subtitles a little up then it's good.(For example you can see nPlayer) 👍

**Comment by itszechs** [comment]
Not sure about streaming from archives but yeah subtitles do need to be adjusted when apply `fit-to-screen` , will look into that

**Comment by itszechs** [comment]
Duplicate https://github.com/itszechs/DriveStream/issues/98
