### ISSUE TITLE
Request to add a slot to input our own client id and secret in app itself

### ISSUE THREAD

**Issue by DiwanshuBRC** [itszechs/DriveStream#73]
Not sure how to add client id in local.properties to be able to use app after recent google changes and rclone client-id being nonstop rate limited.
If possible add an area like Enter Authorisation code type where we can input our own client-id and stuff to be able to login post recent changes.

**Comment by itszechs** [comment]
Yeah, been thinking of doing that.

**Comment by DiwanshuBRC** [comment]
Now facing these error 403 nonstop any help on how to add our own web application client id instead of using rclone, can't seem to understand the way of adding newly created client id into app after doing [#making-your-own-client-id](https://rclone.org/drive/#making-your-own-client-id)

**Comment by itszechs** [comment]
Yup, this is getting really annoying now, I'll try to push a fix as soon as I can. Apologies for lack of updates. Community projects as a job hunting student isn't easy.
