### ISSUE TITLE
In Android 8 OS not INSTALL 

### ISSUE THREAD

**Issue by Learner00100** [itszechs/DriveStream#74]
Hi thanks for recent key update.
I already using this app in my android tv version 9 (installed armeabi v7a).
Today I installed app on my android tv box (Mecool km8) Android version 8, it giving error while installing (problem in paraing the package) tried all, including universal version also .so kindly include support for lower Android version.

**Comment by Learner00100** [comment]
@itszechs I tried to change SDK version, but getting this error (mpv:mergeDebugJniLibFolders FAILED )

So kindly give support for lower version, if mpv lib won't support for Android 8, kindly give drivestream with exoplayer alone in this thread.

Thank you

**Comment by Learner00100** [comment]
@itszechs in next update please give support from Android 5 or 8

**Comment by itszechs** [comment]
> I tried to change SDK version, but getting this error (mpv:mergeDebugJniLibFolders FAILED )

There was an issue building the project on Windows, it has been fixed #79.
Please clone the repo again and try again.

**Comment by Learner00100** [comment]
@itszechs thanks , now in windows app complied success.
I also added client I'd and client secret in local properties.
But now I am getting this error while login.

"Access blocked: This app’s request is invalid

You can’t sign in because this app sent an invalid request. You can try again later or contact the developer about this issue. Learn more about this error
If you are a developer of this app, see error details.
Error 400: redirect_uri_mismatch"

**Comment by itszechs** [comment]
Yes the documentation needs to be updated.

You're supposed to add `http://127.0.0.1:53682` in "Authorized redirect uri", where you created your OAuth Client.

Additionally, please also check Testing/Production status under "OAuth consent screen".
