### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by DeadMan30** [itszechs/DriveStream#75]
Having Authorisation Error While doing Sign in the app!
Android Version: 12

[IMG_20221219_174726](https://user-images.githubusercontent.com/95632062/208424882-f3654003-77ca-49dc-a8a4-b9c23d5ec719.jpg)

**Comment by itszechs** [comment]
duplicate of #72

**Comment by itszechs** [comment]
Please refer to this for current solution: https://github.com/itszechs/DriveStream/issues/72#issuecomment-1342798266

Note: #73 new changes will be made to simply the solution further,
