### ISSUE TITLE
Video tutorials for Add  in local.properties

### ISSUE THREAD

**Issue by Learner00100** [itszechs/DriveStream#76]
Where to find local.properties, to change client id and secret.
If possible put video tutorials or instruction to find local properties.
Also if #73 is implemented, it is more easy as we don't need build apk, as myself also not familiar with apk build from given source code.

**Comment by itszechs** [comment]
Video tutorial won't be possible, please refer to this answer on [StackOverflow](https://stackoverflow.com/a/71795463)
