### ISSUE TITLE
Parsing problem while installing 

### ISSUE THREAD

**Issue by BIGEAZY289** [itszechs/DriveStream#81]
Hi I am using redmi note 4 and I am not able to install this app on the Device getting parsing issue while installing.

**Comment by itszechs** [comment]
What's your Android version?

What version of the app were you trying to install?

Was this an update? Were you trying to install over another version?

**Comment by BIGEAZY289** [comment]
No my android vr is 7 and i tried to install the recent update

**Comment by BIGEAZY289** [comment]
Tried old version but still same issue

**Comment by BIGEAZY289** [comment]
![Screenshot_2023-01-06-11-12-36-890_com google android packageinstaller](https://user-images.githubusercontent.com/67136842/210938036-c191e721-9194-4a60-80ac-51b196801014.jpg)

**Comment by itszechs** [comment]
This app is not supported for Android 7.

Minimum Android Version required for this app is Android 9 (Pie).
