### ISSUE TITLE
Request (If possible) 

### ISSUE THREAD

**Issue by Lucky-069** [itszechs/DriveStream#83]
Hie, I have been using your app and it works fluently and I love it. I was wondering if it was possible to make a plugin of this app for [CloudStream](www.cloudstream.cf). Would love it, if it's possible! Please do look into it. If it's possible! Thank you!

**Comment by itszechs** [comment]
[CloudStream](https://github.com/recloudstream/cloudstream) and this are completely different apps, I do not see how this can be made into an extension to that app

**Comment by Lucky-069** [comment]
Well idk much about coding, but they do have their own plugins and extentions which are used for scraping from sites. So I wondering if you could use the same to make the app.. Did you check their github?

**Comment by itszechs** [comment]
The app you're mentioning uses extensions for scraping websites, whereas this app is just a Google Drive app.
