### ISSUE TITLE
Bug in save last position

### ISSUE THREAD

**Issue by Learner00100** [itszechs/DriveStream#90]
From recent code.
If we play a movie using exoplayer and exit in half runtime, then again playing the same using exoplayer it start from beginning, as exoplayer not saving the last position properly.

But if we play a movie 1st using mpv, then exit at half runtime, then it resume from that position in both mpv also exoplayer.

**Comment by itszechs** [comment]
Hey, thanks for reporting this bug. It has been fixed, can you try [patch-remember-playback](/itszechs/DriveStream/tree/patch-remember-playback) branch and confirm?

**Comment by Learner00100** [comment]
@itszechs 
I'm away from my pc, will complie and tell later
If need to test urgent , you may share apk of that branch,so that test now and tell

**Comment by itszechs** [comment]
No worries, will be waiting for your response. Thank you.

**Comment by Learner00100** [comment]
> No worries, will be waiting for your response. Thank you.

Checked the bug is cleared.
Thanks 
You can merge with main branch.

**Comment by itszechs** [comment]
Thanks mate!
