### ISSUE TITLE
Downloads Section

### ISSUE THREAD

**Issue by rinrinx** [itszechs/DriveStream#93]
Can you add this part?  For example, in order to be able to download and watch certain videos when there is no Internet, and after watching them we can delete them from the phone memory again😁😁😁

**Comment by itszechs** [comment]
@rinrinx Apologies for the delayed response. I appreciate your suggestion, but currently, the primary focus of this app is to enable streaming of original files, addressing a specific issue with the official app.

For offline usage, I recommend utilizing the official Google Drive app or website to download files locally.
