### ISSUE TITLE
Access Blocked

### ISSUE THREAD

**Issue by Kira-0007** [itszechs/DriveStream#99]
![Screenshot_2023-02-20-12-20-04-531-edit_org mozilla firefox](https://user-images.githubusercontent.com/105588608/220033723-861c32b5-2c49-4543-8d5b-09e1ac45c756.jpg)
![Screenshot_2023-02-20-12-19-38-275_org mozilla firefox](https://user-images.githubusercontent.com/105588608/220033742-5b9f95ab-f99e-4db0-89e7-a4b2ee1e267e.jpg)

Even though i account haven't give any permission to rclone still its showing error of access Blocked... Please help

**Comment by Kira-0007** [comment]
But i have not sing in this mail id to any other device for drive stream

I ma using this for first time still getting this error

**Comment by itszechs** [comment]
Your email address has nothing to do with this, this error occurred due to the high number of people logging-in in a short period of time.

**Comment by Kira-0007** [comment]
Oh is that so... Okk thank you.. i thought my mail id has some problem 😃

**Comment by itszechs** [comment]
Yes, closing this as resolved
